# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Run Jekyll on Windows'
url:              
baseurl:          /

github:
  repo:           

author:
  name:           ''
  url:            
