# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'JusticeSeeker'
url:              
baseurl:          /dm_project_site

github:         
  repo:           https://github.com/ulc5410/dm_project_site
  baseurl:        /dm_project_site

author:
  name:           ''
  url:            
